//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blindspot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringStore {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringStore() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blindspot.StringStore", typeof(StringStore).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred.
        /// </summary>
        internal static string AnUnexpectedErrorOccurred {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blindspot is already running.
        /// </summary>
        internal static string BlindspotIsAlreadyRunning {
            get {
                return ResourceManager.GetString("BlindspotIsAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        internal static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot dismiss buffer .
        /// </summary>
        internal static string CannotDismissBuffer {
            get {
                return ResourceManager.GetString("CannotDismissBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical error: .
        /// </summary>
        internal static string CriticalError {
            get {
                return ResourceManager.GetString("CriticalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during load: .
        /// </summary>
        internal static string ErrorDuringLoad {
            get {
                return ResourceManager.GetString("ErrorDuringLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting program.
        /// </summary>
        internal static string ExitingProgram {
            get {
                return ResourceManager.GetString("ExitingProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item activated.
        /// </summary>
        internal static string ItemActivated {
            get {
                return ResourceManager.GetString("ItemActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading playlist.
        /// </summary>
        internal static string LoadingPlaylist {
            get {
                return ResourceManager.GetString("LoadingPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading playlists.
        /// </summary>
        internal static string LoadingPlaylists {
            get {
                return ResourceManager.GetString("LoadingPlaylists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in to Spotify.
        /// </summary>
        internal static string LoggedInToSpotify {
            get {
                return ResourceManager.GetString("LoggedInToSpotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in.
        /// </summary>
        internal static string LoggingIn {
            get {
                return ResourceManager.GetString("LoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in failure: .
        /// </summary>
        internal static string LogInFailure {
            get {
                return ResourceManager.GetString("LogInFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Louder.
        /// </summary>
        internal static string Louder {
            get {
                return ResourceManager.GetString("Louder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more search results.
        /// </summary>
        internal static string MoreSearchResults {
            get {
                return ResourceManager.GetString("MoreSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description available.
        /// </summary>
        internal static string NoDescriptionAvailable {
            get {
                return ResourceManager.GetString("NoDescriptionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No search results.
        /// </summary>
        internal static string NoSearchResults {
            get {
                return ResourceManager.GetString("NoSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No search text.
        /// </summary>
        internal static string NoSearchText {
            get {
                return ResourceManager.GetString("NoSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No track currently being played.
        /// </summary>
        internal static string NoTrackCurrentlyBeingPlayed {
            get {
                return ResourceManager.GetString("NoTrackCurrentlyBeingPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No track information. This is embarrassing..
        /// </summary>
        internal static string NoTrackInformation {
            get {
                return ResourceManager.GetString("NoTrackInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No username or password.
        /// </summary>
        internal static string NoUsernameOrPassword {
            get {
                return ResourceManager.GetString("NoUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops!.
        /// </summary>
        internal static string Oops {
            get {
                return ResourceManager.GetString("Oops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing.
        /// </summary>
        internal static string Playing {
            get {
                return ResourceManager.GetString("Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to playlists loaded.
        /// </summary>
        internal static string PlaylistsLoaded {
            get {
                return ResourceManager.GetString("PlaylistsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a username and password to login to Spotify.
        /// </summary>
        internal static string PleaseEnterAUsernameAndPasswordToLoginToSpotify {
            get {
                return ResourceManager.GetString("PleaseEnterAUsernameAndPasswordToLoginToSpotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter some search text to search for.
        /// </summary>
        internal static string PleaseEnterSomeSearchTextToSearchFor {
            get {
                return ResourceManager.GetString("PleaseEnterSomeSearchTextToSearchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem loading browser.
        /// </summary>
        internal static string ProblemLoadingBrowser {
            get {
                return ResourceManager.GetString("ProblemLoadingBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quieter.
        /// </summary>
        internal static string Quieter {
            get {
                return ResourceManager.GetString("Quieter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for.
        /// </summary>
        internal static string SearchFor {
            get {
                return ResourceManager.GetString("SearchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        internal static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results.
        /// </summary>
        internal static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming error.
        /// </summary>
        internal static string StreamingError {
            get {
                return ResourceManager.GetString("StreamingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tracks loaded.
        /// </summary>
        internal static string TracksLoaded {
            get {
                return ResourceManager.GetString("TracksLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to play track: .
        /// </summary>
        internal static string UnableToPlayTrack {
            get {
                return ResourceManager.GetString("UnableToPlayTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error.
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred..
        /// </summary>
        internal static string UnexpectedErrorOccurred {
            get {
                return ResourceManager.GetString("UnexpectedErrorOccurred", resourceCulture);
            }
        }
    }
}
